# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20180814_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='selected_algo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
